config/routes.rb
Depot::Application.routes.draw do

  resources :accounts

  get "admin" => "admin#index"

  controller :sessions do
    get 'login' => :new
    get 'new_user' => :new_user
    post 'new_user' => :register
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :favorites
  
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

    root :to => 'store#index', :as => 'store'

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :email, :location, :name, :telphone
  belongs_to :user
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items

  def add_product(product_id)
  	current_item = line_items.find_by_product_id(product_id)
  	if current_item
  		current_item.quantity += 1
  	else
  		current_item = line_items.build(:product_id => product_id)
      current_item.price = current_item.product.price
  	end
  	current_item
  end
  
  def total_price
    # price = 0
    #   line_items.each do |line_item|
    #   price += line_item.total_price
    # end
    # price

    line_items.sum {|line_item| line_item.total_price}
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	has_one :product
    attr_accessible :product_id, :user_id

  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :product, :quantity
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :user
  attr_accessible :address, :email, :name, :pay_type
  validates :address, :email, :name, :pay_type, :presence => true
  PAYMENT_TYPES = ["Check", "Credit Card", "Purchase Order"]
  validates :pay_type, :inclusion => PAYMENT_TYPES
  

  def add_line_items_from_cart(cart)
  	cart.line_items.each do |item|
  		item.cart.id = nil
  		line_items << item
  	end
  end


end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :line_items
  belongs_to :favorite
  
  attr_accessible :description, :image_url, :price, :title, :category
  CATEGORY = ['Fiction','Historical','Literature','Science','Law','Educational']
  validates :description, :image_url, :title, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :title, :length => { :minimum => 10 }

  before_destroy :ensure_not_referenced_by_any_line_item

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'line items present')
      return false
    end
  end

  def self.search(search)
    if search
      where("title LIKE?", "%#{search}%")
    else
      all
    end
  end

end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  has_many :orders, :dependent => :destroy
  has_many :favorites
  has_one  :account, :foreign_key => "user_id"

  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessible :password, :password_confirmation, :name, :hashed_password,:salt,:admin

  validate :password_must_be_present



  

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end


  def password
    @password
  end

  def password=(password)
	  @password = password

	  if password.present?
	    generate_salt
	    self.hashed_password = self.class.encrypt_password(password, salt)
	  end

  end

  def User.authenticate(name, password)
	  if user = find_by_name(name)
	    if user.hashed_password == encrypt_password(password, user.salt)
	    user
	  end
   end  
  end
  
  private

  def password_must_be_present
    errors.add(:password, "Missing password") unless hashed_password.present?
  end
  
  def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@total_orders   = Order.count
  	@total_products = Product.count
  	@total_users    = User.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to(store_url, :notice => "Your cart is empty currently!") }
      format.js
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<p class="text-info"><h1>Welcome!</h1></p>
It's <%= Time.now %>

<ul><h4>
<li>We have <%= link_to pluralize(@total_orders, "order"), orders_path %>.</li></br>
<li>We have <%= link_to pluralize(@total_products, "product"),
    products_path %>.</li></br>
<li>We have <%= link_to pluralize(@total_users, "user"),
    users_path %>.</li>
<h4></ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= bootstrap_flash %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <a class="brand" href="#">Rails project</a>
       <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Store", store_url %></li>
            <li><%= link_to "Users", users_url %></li>
            <li><%= link_to "Orders", orders_url %></li>
            <li><a href="#myModal" data-toggle="modal">Cart</a></li>
            <li><%= link_to "My favorites", favorites_url %></li>
            <% if session[:user_id] == nil %>
                <li><%= link_to "Sign in", login_url %></li> 
                <li><%= button_to "CREATE ACCOUNT", new_user_path, :class => 'btn'%></li>
            <% else %>
                <li><%= link_to "Sign out", logout_path, :method => :delete %></li>  
                <a class="brand pull-right" href="#">Welcome!<%= link_to(User.find(session[:user_id]).name, new_account_path) %></a>         
            <% end %>
          </ul>
        </div>
        
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row-fluid">      
      <div class="span3">
        <div class="tabbable table-bordered tabs-left nav-tabs">
          <ul class="nav nav-pills   nav-stacked">
            <li class="active"><a href="#tab1" data-toggle="tab">All books</a></li>
            <li><a href="#tab1" data-toggle="tab">Fiction</a></li>
            <li><a href="#tab2" data-toggle="tab">Historical</a></li>
            <li><a href="#tab3" data-toggle="tab">Literature</a></li>
            <li><a href="#tab4" data-toggle="tab">Science</a></li>
            <li><a href="#tab5" data-toggle="tab">Law</a></li>
            <li><a href="#tab6" data-toggle="tab">Educational</a></li>
          </ul>
          <div class="tab-content">
          </div>


       </div>
        <h4><%= Time.now %><h4>
        <h2>About Us</h2>
        <h4><address>
          <strong>Liu Xingqi</strong><br>
          <a href=''>https://github.com/liuxingqi</a>
          <% if session[:counter] > 5 %>
          <h5>User accessed numbers:  <%= session[:counter] %></h5>
          <% end %>
        </address></h4>
      </div>
      <div class="span9"><%= yield %></div>
    </div>
  </div>
</body>
</html>



 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Shopping cart</h3>
  </div>
  <div class="modal-body">
    <div id="tabbable">
      <% if @cart %> 
            <%= render @cart %>
            <% end %>
        </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
<!--     <button class="btn btn-primary">Save changes</button> -->
  </div>
</div>