config/routes.rb
Depot::Application.routes.draw do

  resources :accounts

  get "admin" => "admin#index"

  controller :sessions do
    get 'login' => :new
    get 'new_user' => :new_user
    post 'new_user' => :register
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :favorites
  
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

    root :to => 'store#index', :as => 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :product, :quantity
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/controllers/line_items_controller.rb
  class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    session[:counter] = 0
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    @cart = current_cart

    respond_to do |format|
      format.html { redirect_to store_url }
      format.js
      format.json { head :no_content }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
l<%= form_for @line_item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :product_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :product_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cart_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :cart_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                line_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr class='success'> 
     <td><%= line_item.product.title %> </td>
     <td><%= line_item.quantity %> </td>
     <td><%= number_to_currency(line_item.total_price) %> </td>
     <td><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              line_item,
              :method => 'delete',
              :remote => true,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger btn-mini' %></td>
</tr>

app/views/line_items/create.js.erb
$('#tabbable').html("<%=j render @cart %>").show();
$('#tabbable').html("<%=j render @cart %>");

app/views/line_items/destroy.js.erb
$('#tabbable').html("<%=j render @cart %>");

app/views/line_items/edit.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/line_items/index.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:cart_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= link_to line_item.id, line_item_path(line_item) %></td>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= line_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_line_item_path(line_item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      line_item_path(line_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_line_item_path,
            :class => 'btn btn-primary' %>

app/views/line_items/new.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/line_items/show.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @line_item.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cart_id) %>:</strong></dt>
  <dd><%= @line_item.cart_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              line_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_line_item_path(@line_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              line_item_path(@line_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>