config/routes.rb
Depot::Application.routes.draw do

  resources :accounts

  get "admin" => "admin#index"

  controller :sessions do
    get 'login' => :new
    get 'new_user' => :new_user
    post 'new_user' => :register
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :favorites
  
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

    root :to => 'store#index', :as => 'store'

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_filter :authorize

  def index
    @products = Product.all
    @science  = Product.where("category = ?", "Science")
    @cart = current_cart
    if session[:counter].nil?
      session[:counter] = 0
    else
      session[:counter] += 1
    end
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<%= form_tag products_path, :method => 'get', :class => 'form-search' do %>
  <p>
<%= text_field_tag :search, params[:search], :class => 'span6' %>    <%= submit_tag "Search", :class => "btn btn-info"%>
  </p>
<% end %>

 <div class='row-fluid'>
 <ul class="thumbnails">
	<% @products.each do |product| %>
       <li class="span4 text-center">
      	<div class="thumbnail">
         <%= link_to image_tag(product.image_url, size: '350x250'), product_url(product) %>
        <h5><%= product.title %></h5>
        <strong><%= number_to_currency(product.price) %></strong>
      </div>
        </li>    
 <% end %>
 </ul>
</div>